models/Marcadores.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "marcadores".
 *
 * @property int $id
 * @property string|null $nombre
 * @property string|null $enlace
 * @property string|null $descripcion_corta
 * @property string|null $descripcion_larga
 * @property string|null $tipo
 */
class Marcadores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'marcadores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tipo'], 'string'],
            [['nombre', 'enlace', 'descripcion_corta'], 'string', 'max' => 255],
            [['descripcion_larga'], 'string', 'max' => 4096],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'enlace' => 'Enlace',
            'descripcion_corta' => 'Descripcion Corta',
            'descripcion_larga' => 'Descripcion Larga',
            'tipo' => 'Tipo',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Marcadores;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $query = Marcadores::find()->select("marcadores.*")->where("tipo = 'Publico'");
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('index',[
            'dataProvider' => $dataProvider,
            'publicos' => 'active',
            'privados' => '',
            'admin' => '',
        ]);
    }

    public function actionPrivados()
    {
        $query = Marcadores::find()->select("marcadores.*");
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('index',[
            'dataProvider' => $dataProvider,
            'publicos' => '',
            'privados' => 'active',
            'admin' => '',
        ]);
    }

    public function actionAdmin()
    {
        $this->layout = 'admin';
        $query = Marcadores::find()->select("marcadores.*");
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('admin',[
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionNuevo()
    {
        $this->layout = 'admin';
        
        return $this->render('nuevo');
    }

}

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
       <div style="text-align: center;">
            <ul class="nav nav-pills" style="display: inline-block;">
                <li role="presentation" class=""><a href="<?=  Url::toRoute(['site/index']) ?>">Publicos</a></li>
                <li role="presentation" class=""><a href="<?=  Url::toRoute(['site/privados']) ?>">Privados</a></li>
                <li role="presentation" class="active"><a href="#">Admin</a></li>
            </ul>
        </div>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Oscar Megía López 2020</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Oscar Megía López 2020</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/admin.php
<?php

/* @var $this yii\web\View */

$this->title = 'Página principal';
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<?php
$form = ActiveForm::begin([
    'action' =>['/site/nuevo']
]); ?>
<button class="btn btn-default btn-primary pull-right" type="submit" style="margin-bottom: 20px;">Nuevo</button>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'enlace',
        'descripcion_corta',
    ],
    'layout' => '{items}',
]) ?>
<button class="btn btn-default btn-primary pull-right" type="submit">Nuevo</button>
<?php
ActiveForm::end();
?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Página principal';
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

$script = "$('#myModal').on('show.bs.modal', function (event) {
  var link = $(event.relatedTarget) // Button that triggered the modal
  var recipient = link.data('descripcion_larga') // Extract info from data-* attributes
  var url = link.data('url') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  var btnVisitar =$('#btnVisitar')
  modal.find('.modal-body').html(recipient)
  btnVisitar.attr('data-url', url);
})";

$this->registerJs($script);

$script2 = "$('#btnVisitar').click(function() {
  var btnVisitar = $(this)
  // Funciona ir a la página anterior
  window.location.href = btnVisitar.attr('data-url');
})";

$this->registerJs($script2);
?>
<div style="text-align: center;">
    <ul class="nav nav-pills" style="display: inline-block;">
        <li role="presentation" class="<?= $publicos ?>"><a href="<?=  Url::toRoute(['site/index']) ?>">Publicos</a></li>
        <li role="presentation" class="<?= $privados ?>"><a href="<?=  Url::toRoute(['site/privados']) ?>">Privados</a></li>
        <li role="presentation" class="<?= $admin ?>"><a href="<?=  Url::toRoute(['site/admin']) ?>">Admin</a></li>
    </ul>
</div>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        [
            'label' => 'Enlace',
            'format' => 'raw',
            'value' => function($data) {
                return Html::a($data->enlace, $data->url, ['target' => '_blank']);
            }
        ],
        [
            'label' => 'Descripción',
            'format' => 'raw',
            'value' => function($data) {
                return Html::a($data->descripcion_corta, '#',
                        ["data-toggle" => "modal", "data-target" => "#myModal",  "data-descripcion_larga" => "$data->descripcion_larga", "data-url" => "$data->url"]);
            }
        ],
    ]
]) ?>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Descripcion</h3>
      </div>
      <div class="modal-body">
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button id="btnVisitar" type="button" class="btn btn-default btn-primary" data-dismiss="modal" data-url="">Visitar</button>
      </div>
    </div>
  </div>
</div>

views/site/nuevo.php
<?php
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'action' =>['/site/nuevo']
]); ?>

<label for="idNombre">Nombre</label>
<input id="idNombre" type="text" name="nombre">
<label for="idDescripcion_corta">Descripcion corta</label>
<input id="idDescripcion_corta" type="text" name="descripcion_corta">
<label for="idDescripcion_larga">Descripcion larga</label>
<input id="idDescripcion_larga" type="text" name="descripcion_larga">
<label for="idPrivado">Privado</label>
<select name="idPrivado">
<option value="1" selected>No</option>
<option value="2">Si</option>
</select>

<?php ActiveForm::end(); ?>